export const INCREEMENT_QUANTITY = 'INCREEMENT_QUANTITY';
export const DECREEMENT_QUANTITY = 'DECREEMENT_QUANTITY';
export const TOTAL_ITEMS = 'TOTAL_ITEMS';
export const TOTAL_AMOUNT = 'TOTAL_AMOUNT';
